// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBh5WXfRQfpHH256DspA-YdC5paumJowg',
    appId: '1:370989705252:web:11830e1338d9e071eb90b1',
    messagingSenderId: '370989705252',
    projectId: 'link-hive-42c6f',
    authDomain: 'link-hive-42c6f.firebaseapp.com',
    storageBucket: 'link-hive-42c6f.firebasestorage.app',
    measurementId: 'G-4ZBYJR1H1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx86-14ItfJfvQm4M99M0yuMJRqdDBL0I',
    appId: '1:370989705252:android:db9c01cfe14af07feb90b1',
    messagingSenderId: '370989705252',
    projectId: 'link-hive-42c6f',
    storageBucket: 'link-hive-42c6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgJURByMpIXxJfnADJ0y8V-SUNTSldwiw',
    appId: '1:370989705252:ios:f2be18d8673aed01eb90b1',
    messagingSenderId: '370989705252',
    projectId: 'link-hive-42c6f',
    storageBucket: 'link-hive-42c6f.firebasestorage.app',
    iosBundleId: 'com.link.hive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgJURByMpIXxJfnADJ0y8V-SUNTSldwiw',
    appId: '1:370989705252:ios:f2be18d8673aed01eb90b1',
    messagingSenderId: '370989705252',
    projectId: 'link-hive-42c6f',
    storageBucket: 'link-hive-42c6f.firebasestorage.app',
    iosBundleId: 'com.link.hive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBh5WXfRQfpHH256DspA-YdC5paumJowg',
    appId: '1:370989705252:web:bdc2ea83117d177beb90b1',
    messagingSenderId: '370989705252',
    projectId: 'link-hive-42c6f',
    authDomain: 'link-hive-42c6f.firebaseapp.com',
    storageBucket: 'link-hive-42c6f.firebasestorage.app',
    measurementId: 'G-7XDE81KYHP',
  );
}
